### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Muneebing** [ECSHackWeek/impedance.py#203]
**Describe the bug**
Hello,
I was trying to fit the model by doing this example data set given on the website, as I am a new user so I was trying to get my head around by applying this example but during the Step of circuit Fit with method .fit() I got the error, please look at the screen shot below.
Could you please tell me what the problem here is?
It says TypeError ('length of impedance and frequencies do not match')
![Bildschirmfoto 2022-05-09 um 13 27 57](https://user-images.githubusercontent.com/105212042/167400824-9a8f929f-0ef0-4b5c-a07d-e34108da2806.png)

**Comment by BGerwe** [comment]
It sounds like the arrays of impedance data and the frequency list are different sizes. Can you show the code used to import the data?

**Comment by Muneebing** [comment]
Hello Brian Thanks for the response, please have a look at the code below.
Thanks.
<img width="1400" alt="Bildschirmfoto 2022-05-09 um 19 46 30" src="https://user-images.githubusercontent.com/105212042/167467510-5c783b16-ab87-440f-b294-47d926d76d4c.png">

**Comment by BGerwe** [comment]
I'm having trouble reproducing the error you're seeing. But I did notice a small typo in your code. In the first set of parallel elements, they should be separated by a comma (`p(R1,C1)`) instead of a dash (`p(R1-C1)`). 

The error message I got using your original circuit string was "UnboundLocalError: local variable 'split' referenced before assignment", and it looks like your original screenshot also shows "UnboundLocalError" at the top of the traceback.

Can you give this a shot and see if it helps?

**Comment by BGerwe** [comment]
The other thing I'm wondering is what dataset you are using. Did you take our [exampleData.csv](https://github.com/ECSHackWeek/impedance.py/blob/9c28fc43bf1b9bf2ee230722defd8b8921ce34f4/data/exampleData.csv) and rename it? Or is the file your own? It seems like the array lengths in the screenshot above don't match up with our example data.

**Comment by Muneebing** [comment]
Thanks a lot Brain for catching the Typo, The problem was the wrong definition of parallel RC element. Its resolved now
